### ISSUE TITLE
Invalid user name when update issue

### ISSUE THREAD

**Issue by hoavq214** [atomita/backlog-v2#3]
1. I am using API Key of user AAA
2. After I'm auth to website using Backlog API by login with Backlog using user BBB
3. User BBB update actualHours of issue (http://developer.nulab-inc.com/docs/backlog/api/2/update-issue)

**Actual result:**
On comment of issue is user AAA updated.

**Expected result:**
User BBB updated.

Pls help! Thanks

**Comment by atomita** [comment]
Hi @hoavq214 ,

Please show me program if possible.
Perhaps, I think that it is the specification of the REST API.

Regards,
atomita
